=== UO294665/SEW/xml/circuito.xsd
<?xml version="1.0" encoding="Windows-1252"?>
<xs:schema xmlns="http://www.uniovi.es" elementFormDefault="qualified" targetNamespace="http://www.uniovi.es" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="circuitos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="circuito" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="circuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="longitud_circuito" />
				<xs:element ref="anchura" />
				<xs:element ref="fecha" />
				<xs:element ref="hora" />
				<xs:element ref="vueltas" />
				<xs:element ref="localidad" />
				<xs:element ref="pais" />
				<xs:element minOccurs="0" maxOccurs="1" ref="patrocinador" />
				<xs:element minOccurs="0" maxOccurs="1" ref="referencias" />
				<xs:element minOccurs="0" maxOccurs="1" ref="fotografias" />
				<xs:element minOccurs="0" maxOccurs="1" ref="videos" />
				<xs:element ref="origen" />
				<xs:element ref="tramos" />
				<xs:element ref="vencedor" />
				<xs:element ref="tiempo_carrera" />
				<xs:element ref="clasificacion" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombre" type="xs:string" />
	<xs:element name="longitud_circuito">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:positiveInteger">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="anchura">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:positiveInteger">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="fecha" type="xs:date" />
	<xs:simpleType name="formatoHora">
		<xs:restriction base="xs:NMTOKEN">
			<xs:enumeration value="12"/>
			<xs:enumeration value="24"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="hora">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:time">
					<xs:attribute name="formato" type="formatoHora" default="24"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="vueltas" type="xs:positiveInteger" />
	<xs:element name="localidad" type="xs:string" />
	<xs:element name="pais" type="xs:string" />
	<xs:element name="patrocinador" type="xs:string" />
	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencia" type="xs:string" />
	<xs:element name="fotografias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="5" ref="fotografia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="fotografia" type="xs:string" />
	<xs:element name="videos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="3" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="video" type="xs:string" />
	<xs:element name="origen">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="latitud" />
				<xs:element ref="longitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="tramos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="tramo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="tramo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="distancia" />
				<xs:element ref="coordenadas" />
				<xs:element ref="sector" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="distancia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:positiveInteger">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="coordenadas">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="latitud" />
				<xs:element ref="longitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="latitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:integer">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="longitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:integer">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="altitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:integer">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="tipoSector">
		<xs:restriction base="xs:positiveInteger">
			<xs:minInclusive value="1"/>
			<xs:maxInclusive value="4"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="sector" type="tipoSector"/>
	<xs:element name="vencedor" type="xs:string" />
	<xs:element name="tiempo_carrera" type="xs:duration" />
	<xs:element name="clasificacion">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="3" ref="piloto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="piloto">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="posicion" type="xs:positiveInteger" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== UO294665/SEW/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<circuitos xsi:schemaLocation="http://www.uniovi.es circuito.xsd"
xmlns:xsi="http://www.w5.org/2001/XMLSchema-instance" xmlns="http://www.uniovi.es">

    <circuito>
        <nombre>Petronas Sepang International Circuit </nombre>
        <longitud_circuito unidad="metros">5543</longitud_circuito>
        <anchura unidad="metros">16</anchura>
        <fecha>2025-10-26</fecha>
        <hora>08:00</hora>
        <vueltas>20</vueltas>
        <localidad>Sepang</localidad>
        <pais>Malasia</pais>
        <patrocinador>Petronas</patrocinador>
        <referencias>
            <referencia>https://www.motogp.com/en/calendar/2025/event/malaysia/c2cd8f49-5643-440f-84fc-4c37b3ef3f87?tab=overview</referencia>
            <referencia>https://en.wikipedia.org/wiki/Sepang_International_Circuit</referencia>
            <referencia>https://www.sepangcircuit.com/</referencia>
        </referencias>
        <fotografias>
            <fotografia>sepang-1.jpg</fotografia>
            <fotografia>sepang-2.jpg</fotografia>
            <fotografia>sepang-3.jpg</fotografia>
        </fotografias>
        <videos>
            <video>sepang-1.mp4</video>
        </videos>
        <origen>
            <latitud unidad = "grados">2.760760</latitud>
            <longitud unidad = "grados">101.738466</longitud>
            <altitud unidad = "metros">36</altitud>
        </origen>
        <tramos>
            <tramo>
                <distancia unidad="metros">626</distancia>
                <coordenadas>
                    <latitud unidad = "grados">2.7603</latitud>
                    <longitud unidad = "grados">101.7328</longitud>
                    <altitud unidad = "metros">37</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>
            <tramo>
                <distancia unidad="metros">38</distancia>
                <coordenadas>
                    <latitud unidad = "grados">2.7606</latitud>
                    <longitud unidad = "grados">101.7325</longitud>
                    <altitud unidad = "metros">37</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>
            <tramo>
                <distancia unidad="metros">32</distancia>
                <coordenadas>
                    <latitud unidad = "grados">2.760846</latitud>
                    <longitud unidad = "grados">101.732708</longitud>
                    <altitud unidad = "metros">37</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>
            <tramo>
                <distancia unidad="metros">31</distancia>
                <coordenadas>
                    <latitud unidad = "grados">2.760933</latitud>
                    <longitud unidad = "grados">101.732970</longitud>
                    <altitud unidad = "metros">37</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>
            <tramo>
                <distancia unidad="metros">61</distancia>
                <coordenadas>
                    <latitud unidad = "grados">2.7608333</latitud>
                    <longitud unidad = "grados">101.7333333</longitud>
                    <altitud unidad = "metros">35</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>
            <tramo>
                <distancia unidad="metros">42</distancia>
                <coordenadas>
                    <latitud unidad = "grados">2.761222</latitud>
                    <longitud unidad = "grados">101.733522</longitud>
                    <altitud unidad = "metros">34</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>
            <tramo>
                <distancia unidad="metros">71</distancia>
                <coordenadas>
                    <latitud unidad = "grados">2.7616667</latitud>
                    <longitud unidad = "grados">101.7330556</longitud>
                    <altitud unidad = "metros">30</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>
            <tramo>
                <distancia unidad="metros">139</distancia>
                <coordenadas>
                    <latitud unidad = "grados">2.7627778</latitud>
                    <longitud unidad = "grados">101.7330556</longitud>
                    <altitud unidad = "metros">24</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>
            <tramo>
                <distancia unidad="metros">109</distancia>
                <coordenadas>
                    <latitud unidad = "grados">2.7636111</latitud>
                    <longitud unidad = "grados">101.7336111</longitud>
                    <altitud unidad = "metros">22</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>
            <tramo>
                <distancia unidad="metros">217</distancia>
                <coordenadas>
                    <latitud unidad = "grados">2.764410</latitud>
                    <longitud unidad = "grados">101.735641</longitud>
                    <altitud unidad = "metros">28</altitud>
                </coordenadas>
                <sector>2</sector>
            </tramo>
            <tramo>
                <distancia unidad="metros">215</distancia>
                <coordenadas>
                    <latitud unidad = "grados">2.765166</latitud>
                    <longitud unidad = "grados">101.737411</longitud>
                    <altitud unidad = "metros">36</altitud>
                </coordenadas>
                <sector>2</sector>
            </tramo>
            <tramo>
                <distancia unidad="metros">28</distancia>
                <coordenadas>
                    <latitud unidad = "grados">2.765050</latitud>
                    <longitud unidad = "grados">101.737633</longitud>
                    <altitud unidad = "metros">37</altitud>
                </coordenadas>
                <sector>2</sector>
            </tramo>
            <tramo>
                <distancia unidad="metros">265</distancia>
                <coordenadas>
                    <latitud unidad = "grados">2.7625000</latitud>
                    <longitud unidad = "grados">101.7380556</longitud>
                    <altitud unidad = "metros">39</altitud>
                </coordenadas>
                <sector>2</sector>
            </tramo>
            <tramo>
                <distancia unidad="metros">73</distancia>
                <coordenadas>
                    <latitud unidad = "grados">2.7622222</latitud>
                    <longitud unidad = "grados">101.7386111</longitud>
                    <altitud unidad = "metros">37</altitud>
                </coordenadas>
                <sector>2</sector>
            </tramo>
            <tramo>
                <distancia unidad="metros">82</distancia>
                <coordenadas>
                    <latitud unidad = "grados">2.7622222</latitud>
                    <longitud unidad = "grados">101.7391667</longitud>
                    <altitud unidad = "metros">36</altitud>
                </coordenadas>
                <sector>2</sector>
            </tramo>
            <tramo>
                <distancia unidad="metros">78</distancia>
                <coordenadas>
                    <latitud unidad = "grados">2.7625000</latitud>
                    <longitud unidad = "grados">101.7397222</longitud>
                    <altitud unidad = "metros">37</altitud>
                </coordenadas>
                <sector>2</sector>
            </tramo>
            <tramo>
                <distancia unidad="metros">83</distancia>
                <coordenadas>
                    <latitud unidad = "grados">2.762955</latitud>
                    <longitud unidad = "grados">101.740617</longitud>
                    <altitud unidad = "metros">38</altitud>
                </coordenadas>
                <sector>2</sector>
            </tramo>
            <tramo>
                <distancia unidad="metros">71</distancia>
                <coordenadas>
                    <latitud unidad = "grados">2.7627778</latitud>
                    <longitud unidad = "grados">101.7411111</longitud>
                    <altitud unidad = "metros">39</altitud>
                </coordenadas>
                <sector>2</sector>
            </tramo>
            <tramo>
                <distancia unidad="metros">235</distancia>
                <coordenadas>
                    <latitud unidad = "grados">2.76111</latitud>
                    <longitud unidad = "grados">101.74250</longitud>
                    <altitud unidad = "metros">39</altitud>
                </coordenadas>
                <sector>2</sector>
            </tramo>
            <tramo>
                <distancia unidad="metros">80</distancia>
                <coordenadas>
                    <latitud unidad = "grados">2.7605556</latitud>
                    <longitud unidad = "grados">101.7430556</longitud>
                    <altitud unidad = "metros">39</altitud>
                </coordenadas>
                <sector>3</sector>
            </tramo>
            <tramo>
                <distancia unidad="metros">109</distancia>
                <coordenadas>
                    <latitud unidad = "grados">2.7597222</latitud>
                    <longitud unidad = "grados">101.7425000</longitud>
                    <altitud unidad = "metros">38</altitud>
                </coordenadas>
                <sector>2</sector>
            </tramo>
            <tramo>
                <distancia unidad="metros">464</distancia>
                <coordenadas>
                    <latitud unidad = "grados">2.759316</latitud>
                    <longitud unidad = "grados">101.738517</longitud>
                    <altitud unidad = "metros">34</altitud>
                </coordenadas>
